lib: [
  "_build/install/default/lib/raylib/META"
  "_build/install/default/lib/raylib/c/libraylib.a" {"c/libraylib.a"}
  "_build/install/default/lib/raylib/c/libraylib_c_stubs.a" {"c/libraylib_c_stubs.a"}
  "_build/install/default/lib/raylib/c/raylib_c.a" {"c/raylib_c.a"}
  "_build/install/default/lib/raylib/c/raylib_c.cma" {"c/raylib_c.cma"}
  "_build/install/default/lib/raylib/c/raylib_c.cmi" {"c/raylib_c.cmi"}
  "_build/install/default/lib/raylib/c/raylib_c.cmt" {"c/raylib_c.cmt"}
  "_build/install/default/lib/raylib/c/raylib_c.cmx" {"c/raylib_c.cmx"}
  "_build/install/default/lib/raylib/c/raylib_c.cmxa" {"c/raylib_c.cmxa"}
  "_build/install/default/lib/raylib/c/raylib_c.cmxs" {"c/raylib_c.cmxs"}
  "_build/install/default/lib/raylib/c/raylib_c.ml" {"c/raylib_c.ml"}
  "_build/install/default/lib/raylib/c/raylib_c__Raylib_c_generated_functions.cmi" {"c/raylib_c__Raylib_c_generated_functions.cmi"}
  "_build/install/default/lib/raylib/c/raylib_c__Raylib_c_generated_functions.cmt" {"c/raylib_c__Raylib_c_generated_functions.cmt"}
  "_build/install/default/lib/raylib/c/raylib_c__Raylib_c_generated_functions.cmx" {"c/raylib_c__Raylib_c_generated_functions.cmx"}
  "_build/install/default/lib/raylib/c/raylib_c_generated_functions.ml" {"c/raylib_c_generated_functions.ml"}
  "_build/install/default/lib/raylib/constants/raylib_generated_constants.a" {"constants/raylib_generated_constants.a"}
  "_build/install/default/lib/raylib/constants/raylib_generated_constants.cma" {"constants/raylib_generated_constants.cma"}
  "_build/install/default/lib/raylib/constants/raylib_generated_constants.cmi" {"constants/raylib_generated_constants.cmi"}
  "_build/install/default/lib/raylib/constants/raylib_generated_constants.cmt" {"constants/raylib_generated_constants.cmt"}
  "_build/install/default/lib/raylib/constants/raylib_generated_constants.cmx" {"constants/raylib_generated_constants.cmx"}
  "_build/install/default/lib/raylib/constants/raylib_generated_constants.cmxa" {"constants/raylib_generated_constants.cmxa"}
  "_build/install/default/lib/raylib/constants/raylib_generated_constants.cmxs" {"constants/raylib_generated_constants.cmxs"}
  "_build/install/default/lib/raylib/constants/raylib_generated_constants.ml" {"constants/raylib_generated_constants.ml"}
  "_build/install/default/lib/raylib/dune-package"
  "_build/install/default/lib/raylib/functions/raylib_c_generated_types.ml" {"functions/raylib_c_generated_types.ml"}
  "_build/install/default/lib/raylib/functions/raylib_functions.a" {"functions/raylib_functions.a"}
  "_build/install/default/lib/raylib/functions/raylib_functions.cma" {"functions/raylib_functions.cma"}
  "_build/install/default/lib/raylib/functions/raylib_functions.cmi" {"functions/raylib_functions.cmi"}
  "_build/install/default/lib/raylib/functions/raylib_functions.cmt" {"functions/raylib_functions.cmt"}
  "_build/install/default/lib/raylib/functions/raylib_functions.cmx" {"functions/raylib_functions.cmx"}
  "_build/install/default/lib/raylib/functions/raylib_functions.cmxa" {"functions/raylib_functions.cmxa"}
  "_build/install/default/lib/raylib/functions/raylib_functions.cmxs" {"functions/raylib_functions.cmxs"}
  "_build/install/default/lib/raylib/functions/raylib_functions.ml" {"functions/raylib_functions.ml"}
  "_build/install/default/lib/raylib/functions/raylib_functions__.cmi" {"functions/raylib_functions__.cmi"}
  "_build/install/default/lib/raylib/functions/raylib_functions__.cmt" {"functions/raylib_functions__.cmt"}
  "_build/install/default/lib/raylib/functions/raylib_functions__.cmx" {"functions/raylib_functions__.cmx"}
  "_build/install/default/lib/raylib/functions/raylib_functions__.ml" {"functions/raylib_functions__.ml"}
  "_build/install/default/lib/raylib/functions/raylib_functions__Raylib_c_generated_types.cmi" {"functions/raylib_functions__Raylib_c_generated_types.cmi"}
  "_build/install/default/lib/raylib/functions/raylib_functions__Raylib_c_generated_types.cmt" {"functions/raylib_functions__Raylib_c_generated_types.cmt"}
  "_build/install/default/lib/raylib/functions/raylib_functions__Raylib_c_generated_types.cmx" {"functions/raylib_functions__Raylib_c_generated_types.cmx"}
  "_build/install/default/lib/raylib/opam"
  "_build/install/default/lib/raylib/raylib.a"
  "_build/install/default/lib/raylib/raylib.cma"
  "_build/install/default/lib/raylib/raylib.cmi"
  "_build/install/default/lib/raylib/raylib.cmt"
  "_build/install/default/lib/raylib/raylib.cmx"
  "_build/install/default/lib/raylib/raylib.cmxa"
  "_build/install/default/lib/raylib/raylib.cmxs"
  "_build/install/default/lib/raylib/raylib.ml"
  "_build/install/default/lib/raylib/types/raylib_types.a" {"types/raylib_types.a"}
  "_build/install/default/lib/raylib/types/raylib_types.cma" {"types/raylib_types.cma"}
  "_build/install/default/lib/raylib/types/raylib_types.cmi" {"types/raylib_types.cmi"}
  "_build/install/default/lib/raylib/types/raylib_types.cmt" {"types/raylib_types.cmt"}
  "_build/install/default/lib/raylib/types/raylib_types.cmx" {"types/raylib_types.cmx"}
  "_build/install/default/lib/raylib/types/raylib_types.cmxa" {"types/raylib_types.cmxa"}
  "_build/install/default/lib/raylib/types/raylib_types.cmxs" {"types/raylib_types.cmxs"}
  "_build/install/default/lib/raylib/types/raylib_types.ml" {"types/raylib_types.ml"}
]
doc: [
  "_build/install/default/doc/raylib/LICENSE"
  "_build/install/default/doc/raylib/README.md"
]
stublibs: [
  "_build/install/default/lib/stublibs/dllraylib.so"
  "_build/install/default/lib/stublibs/dllraylib_c_stubs.so"
]
