name: build

on:
  - push
  - pull_request

jobs:
  build-sdl:
    name: build (SDL2)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install SDL2
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev

      - name: Use OCaml 5.4.1
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.4.1

      - run: opam pin -n -k path .
      - run: opam install -y raylib-options-sdl2 raylib
      - name: Verify SDL2 backend
        run: ldd _opam/lib/stublibs/dllraylib.so | grep -q libSDL2

  build-and-test:
    name: build

    strategy:
      fail-fast: false
      matrix:
        include:
          - { ocaml-compiler: 5.4.1, os: ubuntu-latest }
          - { ocaml-compiler: 5.4.1, os: macos-latest }
          - { ocaml-compiler: 4.14.0, os: ubuntu-latest }
          - { ocaml-compiler: 4.14.0, os: windows-latest }
          - { ocaml-compiler: 4.14.0, os: macos-latest }
          - { ocaml-compiler: 4.11.2, os: ubuntu-latest }

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Re-synchronize the package index files on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam pin -n .

      - run: opam install . --deps-only
      - run: opam install containers re yojson

      - run: opam exec -- dune build
        if: matrix.ocaml-compiler != '4.11.2'

      - run: opam install .
        if: matrix.os != 'windows-latest'
